services:
  wallet-backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/php/src/application
    networks:
      - lendo
    ports:
      - '8000:80'
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'lendo'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3309:3306'
    volumes:
      - lendo:/var/lib/mysql
volumes:
  lendo:
networks:
  lendo:
    external: true
